eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: UserService

  datasource:
    url: jdbc:mysql://localhost:3306/prod_doc_appointment_user_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate.format_sql: true

  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000

server:
  port: 9090
